#
# Makefile to print all files containing documentation for the window handler
# and related programs.
#

FILES = Makefile \
	window_hnd.doc \
	wh_escapes.doc \
	wshpp.doc \
	wsh.doc \
	win_cmds.doc \
	wh_panics

PRINT = print
TOUCH = touch


print: $(FILES)
	$(PRINT) $?
	$(TOUCH) $@
