#
# Makefile to print all the things used to install the window handler.
#

FILES =	Makefile \
	.profile \
	uid.c \
	makebinary \
	makeheader \
	tarbin \
	tarhead \
	tarall \
	cleanup \
	mkwinsystem \
	mkwinuser


print: $(FILES)
	print $?
	touch $@
