#
# Makefile to print all files containing descriptions for the window shell.
# These files must first be processed by the window shell preprocessor.
#

FILES = Makefile \
	simple.wd \
	demo_eng.wd \
	demo_swe.wd \
	comdex_m.wd \
	comdex_d.wd \
	stdsh.wd \
	demo.wd \
	panmenu.wd \
	macintosh.wd



print: $(FILES)
	print $?
	touch $@
